brew "ack"
brew "act"
brew "awscli"
brew "bfg"
brew "ccache"
brew "coreutils"
brew "curl"
brew "entr"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "jq"
brew "mpv"
brew "neovim"
brew "octave"
brew "plantuml"
brew "python"
brew "redis", restart_service: true
brew "rg"
brew "sox"
brew "switchaudio-osx"
brew "tfenv"
brew "tmux"
brew "tree"
brew "uv"
brew "watch"
brew "wget"
brew "yt-dlp"
brew "zoxide"
brew "zsh-syntax-highlighting"
brew "koekeishiya/formulae/skhd"

cask "aldente"
cask "blackhole-2ch"
cask "blender"
cask "brave-browser"
cask "claude"
cask "claude-code"
cask "discord"
cask "docker-desktop"
cask "dropbox"
cask "figma"
cask "firefox"
cask "ghostty"
cask "google-chrome"
cask "ledger-wallet"
cask "loom"
cask "openemu"
cask "postman"
cask "qlmarkdown"
cask "rectangle"
cask "signal"
cask "slack"
cask "spotify"
cask "tableplus"
cask "transmission"
cask "webpquicklook"
cask "zoom"

mas "Adblock Plus", id: 1432731683
mas "Bitwarden", id: 1352778147
mas "MindNode", id: 1289197285
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
